### ISSUE TITLE
Counterpart that allows any type, a la Variant (if possible)

### ISSUE THREAD

**Issue by Abscissa** [s-ludwig/taggedalgebraic#10]
Not sure if this is possible (I'd imagine the implementation would have to be different from the existing `TaggedAlgebraic` and not use an enum to store the type), but it'd be nice to have an equivalent to Phobos's Variant: Ie, A type that would automatically forward function calls like `TaggedAlgebraic` does (unlike Phobos's `Algebraic`), but would accept any type, not just a finite pre-determined set of types.

Even better if it allowed restricting the allowed types via constraints like isForwardRange, etc.

The nice benefit of this (and the use-case I have in mind), is that such a tool would allow choosing between different static types at runtime (including arbitrary new user-defined types), but without resorting to OO class-based wrapper types (like std.digest does, which leads to the mess of having separate template-based and OO-based interfaces for the same thing).

**Comment by s-ludwig** [comment]
`Variant` already kind of does this, but only for certain operators, not for methods in general. It would generally be possible to extend it that way, based on the way it currently works, but it would be rather inefficient, requiring two layers of dynamic dispatch - one using a function pointer and one using a string `switch` statement to switch on the method name, possibly followed by a loop to determine the matching overload. 

I'll close this ticket here, because it is out of the scope of this project. Could make sense to put this up to discussion for Phobos, though.
